### ISSUE TITLE
Force choke 

### ISSUE THREAD

**Issue by Adam1no1** [StarLight-Oliver/AFPS#1]
[ERROR] dvanced force power system/lua/autorun/star_load.lua:337: attempt to call method 'Freeze' (a nil value)
  1. action - addons/[sl]advanced force power system/lua/autorun/star_load.lua:337
   2. unknown - addons/[sl]advanced force power system/lua/weapons/weapon_lightsaber_star.lua:100

**Comment by Bendilin** [comment]
This is a problem with freeze instead of choke, I'm no expert, but i woupd double check that you have this addon installed right.
